* Encoding: UTF-8.

DATASET ACTIVATE DataSet1.
DESCRIPTIVES VARIABLES=A1 A2 A6_1 A3 A4 A5
  /STATISTICS=MEAN STDDEV MIN MAX.

FREQUENCIES VARIABLES=A1 A2 A6_1 A3 A4 A5
  /ORDER=ANALYSIS.

COMPUTE Post_Humanization=MEAN(Post_C1,Post_C2).
EXECUTE.

COMPUTE Post_superordinate=MEAN(Post_C9,Post_C10,Post_D1).
EXECUTE.

COMPUTE Post_emphathy=MEAN(Post_C11,Post_C12,Post_C13).
EXECUTE.

COMPUTE Post_attitude=MEAN(Post_C14,Post_C15,Post_C16,Post_C17,Post_C18).
EXECUTE.

COMPUTE Post_support=MEAN(Post_E1,Post_E2).
EXECUTE.

##Table1

RELIABILITY
  /VARIABLES=Post_C1 Post_C2
  /SCALE('ALL VARIABLES') ALL
  /MODEL=ALPHA
  /STATISTICS=DESCRIPTIVE SCALE
  /SUMMARY=TOTAL.

RELIABILITY
  /VARIABLES=Post_C9 Post_C10 Post_D1
  /SCALE('ALL VARIABLES') ALL
  /MODEL=ALPHA
  /STATISTICS=DESCRIPTIVE SCALE
  /SUMMARY=TOTAL.

RELIABILITY
  /VARIABLES=Post_C11 Post_C12 Post_C13
  /SCALE('ALL VARIABLES') ALL
  /MODEL=ALPHA
  /STATISTICS=DESCRIPTIVE SCALE
  /SUMMARY=TOTAL.

RELIABILITY
  /VARIABLES=Post_C14 Post_C15 Post_C16 Post_C17 Post_C18
  /SCALE('ALL VARIABLES') ALL
  /MODEL=ALPHA
  /STATISTICS=DESCRIPTIVE SCALE
  /SUMMARY=TOTAL.

RELIABILITY
  /VARIABLES=Post_E1 Post_E2
  /SCALE('ALL VARIABLES') ALL
  /MODEL=ALPHA
  /STATISTICS=DESCRIPTIVE SCALE
  /SUMMARY=TOTAL.

##main study post test - manipulation check

T-TEST GROUPS=Info(1 2)
  /MISSING=ANALYSIS
  /VARIABLES=Post_superordinate
  /ES DISPLAY(TRUE)
  /CRITERIA=CI(.95).

##Table3

T-TEST GROUPS=Info(1 2)
  /MISSING=ANALYSIS
  /VARIABLES=Post_Humanization Post_emphathy Post_attitude Post_support Post_F1
  /ES DISPLAY(TRUE)
  /CRITERIA=CI(.95).


COMPUTE Pre_Humanization=MEAN(Pre_C1,Pre_C2).
EXECUTE.

COMPUTE Pre_superordinate=MEAN(Pre_C9,Pre_C10,Pre_D1).
EXECUTE.

COMPUTE Pre_emphathy=MEAN(Pre_C11,Pre_C12,Pre_C13).
EXECUTE.

COMPUTE Pre_attitude=MEAN(Pre_C14,Pre_C15,Pre_C16,Pre_C17,Pre_C18).
EXECUTE.

COMPUTE Pre_support=MEAN(Pre_E1,Pre_E2).
EXECUTE.

##Table4
    
T-TEST PAIRS=Post_Humanization Post_emphathy Post_attitude Post_support Post_F1 WITH Pre_Humanization Pre_emphathy Pre_attitude Pre_support Pre_F1 (PAIRED)
  /ES DISPLAY(TRUE) STANDARDIZER(SD)
  /CRITERIA=CI(.9500)
  /MISSING=ANALYSIS.
